### ISSUE TITLE
Server side ecommerce events are sent to GA with context. Messes up reports

### ISSUE THREAD

**Issue by guillaumecabane** [segment-integrations/integration-google-analytics#6]
I'm a SaaS with recurring revenue handled server-side, as recommended by the Segment documentation. In GA, 75% of my worldwide revenue comes from Bordman, Oregon, USA.
Seems like Segment it passing their IP to GA.
I believe it should not be set, so as to avoid those reporting issues.

**Comment by pauloschilling** [comment]
@guillaumecabane:
> [**Traffic from Boardman or other unusual cities**](https://segment.com/docs/integrations/google-analytics#traffic-from-boardman-or-other-unusual-cities)
> If you are seeing traffic from Boardman or other unusual locations, chances are you are sending calls to Google Analytics from the server side (our AWS servers reside in Boardman, Oregon). In order to prevent this, you would have to manually pass the IP information in the context object from the server.

Unfortunately, even if we send a custom context, there will be this "**Bad Event Tracking Code**" present on Analytics Notifications, saying:
> The Landing Pages report has a `(not set)` entry. Verify that tracking code for property `FOOBAR` sends a `_trackPageview` hit and that it does this before sending any events.

GA is not correlating a previous `analytics.page()` call made from the browser using the same `User-ID` from the server-side `track()`. The problem is that we can't just send a fake server-side `page()` before the `track()`, since on this case, if the customer's first page was "/my-landing", and we record a server-side event for a transaction (payment), the "Landing Page" for this event needs to be the "/my-landing", this way we can measure the conversion for each site page/landing page.

When I first implemented a server-side integration with GA using the Measurement Protocol with PHP, I was manually sending the ID present in the `_ga` cookie, so this way GA was able to do his work, displaying better reports.

@sperand-io @hankim813, any thoughts? I'm not sure if maybe this is also connected to #2.

**Comment by sperand-io** [comment]
@guillaumecabane we don't send our own IP explicitly. Unfortunately, in the absence of one passed explicitly by you (which we'd then include in the [ip field](https://github.com/segmentio/integration-google-analytics/blob/master/lib/mapper.js#L185)), they simply pull the IP off the request itself. Perhaps there's a way for us to instruct them not to do so, but I don't see it in their measurement protocol's [parameter reference docs](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters?hl=en). Otherwise, the best bet here is to make sure you're passing your user's IP from your request context in the calls via `context.ip`

@pauloschilling you can pass the clientId from the browser to GA in the `context["Google Analytics"].clientId` to achieve that linkage in the non-userId enabled report. It's available on the `_ga` cookie as you mentioned or in js via:

```
ga(function(tracker) {
  var clientId = tracker.get('clientId');
});
```

Hope that helps! Let me know if there's anything else I can help with or answer

**Comment by pauloschilling** [comment]
Hi @sperand-io, thank you for the tip, I was considering doing this but just wanted to confirm first, since we need to store the clientId to make sure we will have it for any server-side events triggered by requests made from external services like PayPal's IPN.

Also, this seems to be required for the User-ID enabled view as well, even in there I'm not able to achieve this level of linkage, only for a few things like UTM's and referrers, so GA probably is not able to do everything using just the `user_id`. =/

I'll start sending the clientId from _ga to see what happens.

Best!

**Comment by pauloschilling** [comment]
Hey @sperand-io, just coming back to say that everything is working fine now, the `clientId` was the missing piece to make it 100% functional.

@guillaumecabane, I'm not sure if you're still using Segment + GA, but I highly recommend following the same steps to have your reports returning really accurate information.

Best!

**Comment by sperand-io** [comment]
Glad to hear it :)
