### ISSUE TITLE
Server Side GA with Mobile Source?

### ISSUE THREAD

**Issue by aloisbarreras** [segment-integrations/integration-google-analytics#79]
This is more of asking for a general clarification than an issue.

The GA documentation makes it seem like I should be able to track events from my iOS application _without_ bundling the GA Mobile SDK. My understanding is that events from my iOS app will go through your API and you will broadcast the event to GA from your servers using this integration.

However, I cannot seem to get it to work this way. I thought that the 'channels()' method set for which sources this will integration will broadcast events, but I don't see 'mobile' passed into that method here, so my initial thought is that events are not being broadcast from my iOS app because this is missing 'mobile' passed to channels(). Is my understanding of how this works correct?

I really just want to double check if it's possible to use the server side GA _without_ bundling it into my app and double check my understanding of channels().

**Comment by hankim813** [comment]
hey @aloisbarreras, you should be able to send GA data without bundling. if `channels()` includes `'server'`, it will accept data from mobile libraries. We deprecated `'mobile'` and treat data from server side or mobile libs as a `server` channel.

There could be a number of reasons why this might not be working. Unless you can provide reproducible case I think your best bet is to reach out to the support team since they can better assist your implementation since they will have some boiler plate context like your source info, etc.

You can file a ticket here: https://segment.com/contact/requests/

Make sure you put in the server side tracking ID!
